Retraining2Web/DotNetTraining.Web/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using DotNetTraining.Web.Areas.HelpPage.ModelDescriptions;
using DotNetTraining.Web.Areas.HelpPage.Models;

namespace DotNetTraining.Web.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
        //   : this(GlobalConfiguration.Configuration)
        {
            Configuration = GlobalConfiguration.Configuration;
        }

        //public HelpController(HttpConfiguration config)
        //{
        //    Configuration = config;
        //}

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

Retraining2Web/DotNetTraining.Web/Controllers/AgencyController.cs
using DotNetTraining.ApplicationFacade;
using DotNetTraining.Web.Providers;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace DotNetTraining.Web.Controllers
{
    [Authorize(Roles = "Admins,Agents")]
    public class AgencyController : Controller
    {
        private readonly IAgencyFacade agencyFacade;

        public IConfigurationProvider configProvider { get; }

        public AgencyController(IAgencyFacade agencyFacade, IConfigurationProvider configProvider)
        {
            this.agencyFacade = agencyFacade;
            this.configProvider = configProvider;
        }

        private string LogoFolder()
        {
            return Server.MapPath(configProvider.AgencyLogoFolder);
        }
        private string AgencyLogoFile(AgencyFacadeItem agency)
        {
            string folder = Path.Combine(LogoFolder(), agency.Id.ToString());
            if (!Directory.Exists(folder))
                Directory.CreateDirectory(folder);
            return Path.Combine(folder, agency.LogoImageName);
        }
        [HttpGet]
        public ActionResult Edit()
        {
            var user = HttpContext.User as ClaimsPrincipal;
            int agencyId = int.Parse(user.FindFirst(c => c.Type == ClaimTypes.UserData).Value);

            var agency = agencyFacade.AgencyById(agencyId);
            if (agency == null)
                return new HttpNotFoundResult();

            return View(agency);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AgencyFacadeItem model, HttpPostedFileBase LogoFile)
        {
            if (!ModelState.IsValid)
                return View(model);

            if ((LogoFile != null) && (LogoFile.ContentLength > 0))
            {
                string filePath = AgencyLogoFile(model);
                using (var stream = new FileStream(filePath, FileMode.OpenOrCreate))
                {
                    LogoFile.InputStream.CopyTo(stream);
                }
            }

            agencyFacade.Save(model);
            ViewData["SaveSuccessful"] = "Successful!";
            return View(model);
        }
    }
}

Retraining2Web/DotNetTraining.Web/Controllers/HotelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DotNetTraining.Web.Controllers
{
    public class HotelController : Controller
    {
        // GET: Hotel
        public ActionResult Index()
        {
            return View();
        }
    }
}

Retraining2Web/DotNetTraining.Web/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DotNetTraining.Web.Controllers
{
    public class OrderController : Controller
    {
        // GET: Order
        public ActionResult Index()
        {
            return View();
        }
    }
}

Retraining2Web/DotNetTraining.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    Navigation
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(".Net retraining", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "HelpPage" }, null)</li>

                    @if (User.Identity.IsAuthenticated)
                    {
                        if (User.IsInRole("Admins"))
                        {
                            <li>@Html.ActionLink("Manage Locations", "Index", "Location")</li>
                        }
                        if (User.IsInRole("Admins") || User.IsInRole("Agents"))
                        {
                            <li>@Html.ActionLink("Manage Agency", "Edit", "Agency")</li>
                        }
                        if (User.IsInRole("Admins") || User.IsInRole("Agents"))
                        {
                            <li>@Html.ActionLink("Manage Hotels", "Index", "Hotel")</li>
                        }
                        if (User.IsInRole("Admins"))
                        {
                            <li>@Html.ActionLink("Run Synchronization", "Sync", "Home")</li>
                        }
                        if (User.IsInRole("Admins") || User.IsInRole("Agents"))
                        {
                            <li>@Html.ActionLink("Test Order page", "Index", "Order")</li>
                        }
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        @RenderSection("SPAViews", required: false)
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/vue")
    @Scripts.Render("~/bundles/systemjs")
    @RenderSection("Scripts", required: false)
</body>
</html>